#!/usr/bin/env python

"Make file for book project"

# TODO: logging
# TODO: tests
# TODO: pylint
# TODO: file exceptions
# TODO: per function import exceptions
# TODO: define builder exception
# TODO: Pygments highlighting

import sys

from lib.commands import main

if __name__ == '__main__':
    main(sys.argv[1:])